# Server config
server.port=8081

# Database config
spring.data.mongodb.host=127.0.0.1
spring.data.mongodb.port=27017
#spring.data.mongodb.authentication-database=ws-user-login
spring.data.mongodb.database=ws-user-login
spring.data.mongodb.uri=mongodb://localhost/ws-user-login
