
#Database connection#

## - DEBUG
##spring.data.mongodb.uri=mongodb://localhost:27017/workshop_mongo

## - PRODUCAO
spring.data.mongodb.uri=mongodb+srv://root:genesisfurioso16@apirest-spring-mongo.gln2k.mongodb.net/MomgoDb-Api