spring.application.name=data-automation-project

#define profile for local env
spring.profiles.active=dev


# Database Config
spring.datasource.url=jdbc:postgresql://localhost:5432/data-automation
spring.datasource.username=postgres
spring.datasource.password=root

# PostgreSQL JDBC Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Spring cloud config

# Disable to test in local env
spring.cloud.config.enabled=false


# Spring security config
#spring.security.user.name=admin
#spring.security.user.password=123456

# upload file location
file.upload-dir=C:/data-automation/uploads

# Jwt config
jwt.secret=${JWT_SECRET}
jwt.expiration=360000
jwt.refreshTokenExpiration=360000

